#!/usr/bin/env python3
"""Regenerate the sankey strategy's nav.js + dashboard.html index from the
dated analysis files (YYMMDD_<ticker>.html) present in this folder.

Run after adding a new analysis:
    python3 strategy/sankey/_build.py
"""
import os, re, html as H

HERE = os.path.dirname(os.path.abspath(__file__))
PAT = re.compile(r'^(\d{6})_([A-Za-z0-9.\-]+)\.html$')

items = []
for fn in sorted(os.listdir(HERE)):
    m = PAT.match(fn)
    if not m:
        continue
    yymmdd, tick = m.group(1), m.group(2)
    date = '20' + yymmdd[:2] + '-' + yymmdd[2:4] + '-' + yymmdd[4:6]
    try:
        head = open(os.path.join(HERE, fn), encoding='utf-8').read(4000)
        tm = re.search(r'<title>(.*?)</title>', head, re.S)
        title = tm.group(1).strip() if tm else fn
    except Exception:
        title = fn
    items.append({'file': fn, 'tick': tick.upper(), 'date': date, 'yymmdd': yymmdd, 'title': title})

items.sort(key=lambda x: x['yymmdd'], reverse=True)

# ---- nav.js ----
analyses = ','.join("{file:'%s',label:'%s · %s'}" % (i['file'], i['tick'], i['date']) for i in items)
navjs = '''/* sankey strategy nav (auto-generated by _build.py — do not hand-edit) */
(function(){
  var ANALYSES=[%s];
  var here=(location.pathname.split('/').pop()||'').toLowerCase();
  var links=ANALYSES.map(function(a){return a.file.toLowerCase()===here
    ?'<span class="sk-tab on">'+a.label+'</span>'
    :'<a class="sk-tab" href="'+a.file+'">'+a.label+'</a>';}).join('');
  var css='.sk-nav{font-family:system-ui,-apple-system,"PingFang SC",sans-serif;margin:0 0 14px;display:flex;flex-wrap:wrap;gap:8px;align-items:center}'
    +'.sk-tab{font-size:13px;padding:4px 11px;border:1px solid #e6e9ee;border-radius:7px;background:#fff;color:#5b6573;text-decoration:none}'
    +'.sk-tab.on{background:#eef5fc;border-color:#3b82c4;color:#1f2733;font-weight:700}'
    +'.sk-tab:hover{border-color:#3b82c4;color:#1f2733}.sk-x{margin-left:auto;border-style:dashed}'
    +'.sk-lab{font-size:12px;color:#9aa3ad;font-weight:700;margin-right:2px}';
  var h='<nav class="sk-nav"><span class="sk-lab">\\ud83d\\udcca sankey \\u7b56\\u7565</span>'+links
    +'<a class="sk-tab" href="ARCHITECTURE.html">\\u65b9\\u6cd5\\u8bba</a>'
    +'</nav>';
  var s=document.createElement('style');s.textContent=css;document.head.appendChild(s);
  function mount(){var w=document.querySelector('.wrap')||document.body;w.insertAdjacentHTML('afterbegin',h);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
''' % analyses
open(os.path.join(HERE, 'nav.js'), 'w', encoding='utf-8').write(navjs)

# ---- dashboard.html (index) ----
cards = ''.join(
    '<a class="card" href="%s"><div class="t">%s</div><div class="d">%s</div></a>\n'
    % (i['file'], H.escape(i['tick'] + ' · ' + i['date']), H.escape(i['title']))
    for i in items)
index = '''<!doctype html><html lang="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>sankey 策略 — 单名财报钱流解剖</title>
<style>body{font-family:system-ui,-apple-system,"PingFang SC",sans-serif;background:#f6f8fb;color:#1f2733;margin:0;line-height:1.6}
.wrap{max-width:820px;margin:0 auto;padding:30px 22px}h1{font-size:23px;margin:0 0 6px}
.card{display:block;background:#fff;border:1px solid #e6e9ee;border-radius:12px;padding:15px 18px;margin:14px 0;text-decoration:none;color:inherit}
.card:hover{border-color:#3b82c4}.t{font-weight:800;font-size:17px}.d{color:#5b6573;font-size:13px;margin-top:4px}a{color:#3b82c4}code{background:#eef1f5;padding:1px 5px;border-radius:4px}</style></head>
<body><div class="wrap">
<h1>\U0001f4ca sankey — 单公司财报"钱流"解剖</h1>
<p class="d">桑基图把一家公司的利润表/资产负债表/市值构成画成"水流",加估值诊断和财报事件推演。命名:<code>YYMMDD_ticker.html</code>。</p>
%s
<p class="d"><a href="ARCHITECTURE.html">方法论</a> · <a href="../../index.html">返回首页 ↗</a></p>
</div><script src="nav.js"></script></body></html>
''' % cards
open(os.path.join(HERE, 'dashboard.html'), 'w', encoding='utf-8').write(index)

print('rebuilt nav.js + dashboard.html for %d analyses: %s' % (len(items), [i['file'] for i in items]))
