/* sankey strategy nav (auto-generated by _build.py — do not hand-edit) */
(function(){
  var ANALYSES=[{file:'260610_amat.html',label:'AMAT · 2026-06-10'},{file:'260610_cohr.html',label:'COHR · 2026-06-10'},{file:'260610_fn.html',label:'FN · 2026-06-10'},{file:'260608_vst.html',label:'VST · 2026-06-08'}];
  var here=(location.pathname.split('/').pop()||'').toLowerCase();
  var links=ANALYSES.map(function(a){return a.file.toLowerCase()===here
    ?'<span class="sk-tab on">'+a.label+'</span>'
    :'<a class="sk-tab" href="'+a.file+'">'+a.label+'</a>';}).join('');
  var css='.sk-nav{font-family:system-ui,-apple-system,"PingFang SC",sans-serif;margin:0 0 14px;display:flex;flex-wrap:wrap;gap:8px;align-items:center}'
    +'.sk-tab{font-size:13px;padding:4px 11px;border:1px solid #e6e9ee;border-radius:7px;background:#fff;color:#5b6573;text-decoration:none}'
    +'.sk-tab.on{background:#eef5fc;border-color:#3b82c4;color:#1f2733;font-weight:700}'
    +'.sk-tab:hover{border-color:#3b82c4;color:#1f2733}.sk-x{margin-left:auto;border-style:dashed}'
    +'.sk-lab{font-size:12px;color:#9aa3ad;font-weight:700;margin-right:2px}';
  var h='<nav class="sk-nav"><span class="sk-lab">\ud83d\udcca sankey \u7b56\u7565</span>'+links
    +'<a class="sk-tab" href="ARCHITECTURE.html">\u65b9\u6cd5\u8bba</a>'
    +'</nav>';
  var s=document.createElement('style');s.textContent=css;document.head.appendChild(s);
  function mount(){var w=document.querySelector('.wrap')||document.body;w.insertAdjacentHTML('afterbegin',h);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
