/* sankey strategy nav (auto-generated by _build.py — do not hand-edit) */
(function(){
  var ANALYSES=[{file:'260608_ceg.html',label:'CEG · 2026-06-08'},{file:'260608_vst.html',label:'VST · 2026-06-08'},{file:'260607_fig.html',label:'FIG · 2026-06-07'},{file:'260607_nbis.html',label:'NBIS · 2026-06-07'},{file:'260607_pltr.html',label:'PLTR · 2026-06-07'},{file:'260606_adbe.html',label:'ADBE · 2026-06-06'},{file:'260606_intu.html',label:'INTU · 2026-06-06'},{file:'260606_msft.html',label:'MSFT · 2026-06-06'},{file:'260606_now.html',label:'NOW · 2026-06-06'}];
  var here=(location.pathname.split('/').pop()||'').toLowerCase();
  var links=ANALYSES.map(function(a){return a.file.toLowerCase()===here
    ?'<span class="sk-tab on">'+a.label+'</span>'
    :'<a class="sk-tab" href="'+a.file+'">'+a.label+'</a>';}).join('');
  var css='.sk-nav{font-family:system-ui,-apple-system,"PingFang SC",sans-serif;margin:0 0 14px;display:flex;flex-wrap:wrap;gap:8px;align-items:center}'
    +'.sk-tab{font-size:13px;padding:4px 11px;border:1px solid #e6e9ee;border-radius:7px;background:#fff;color:#5b6573;text-decoration:none}'
    +'.sk-tab.on{background:#eef5fc;border-color:#3b82c4;color:#1f2733;font-weight:700}'
    +'.sk-tab:hover{border-color:#3b82c4;color:#1f2733}.sk-x{margin-left:auto;border-style:dashed}'
    +'.sk-tool{background:#eef7f0;border-color:#bfe3cb;color:#1c8a4e;font-weight:700}.sk-tool:hover{border-color:#1c8a4e;color:#136b3b}'
    +'.sk-lab{font-size:12px;color:#9aa3ad;font-weight:700;margin-right:2px}';
  var h='<nav class="sk-nav"><span class="sk-lab">\ud83d\udcca sankey \u7b56\u7565</span>'+links
    +'<a class="sk-tab" href="ARCHITECTURE.html">\u65b9\u6cd5\u8bba</a>'
    +'<a class="sk-tab sk-tool" href="../vst-leap/index.html" target="_blank" rel="noopener">\ud83c\udfaf VST LEAP \u5de5\u5177 \u2197</a>'
    +'<a class="sk-tab sk-x" href="../price-over-value/dashboard.html">price-over-value \u2197</a>'
    +'<a class="sk-tab" href="../../backtest/dashboard.html">\u56de\u6d4b\u6a21\u7ec4 \u2197</a></nav>';
  var s=document.createElement('style');s.textContent=css;document.head.appendChild(s);
  function mount(){var w=document.querySelector('.wrap')||document.body;w.insertAdjacentHTML('afterbegin',h);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
